package tools

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/pardnchiu/agenvoy/internal/tools/calculate"
	"github.com/pardnchiu/agenvoy/internal/tools/errorMemory"
	"github.com/pardnchiu/agenvoy/internal/tools/external"
	"github.com/pardnchiu/agenvoy/internal/tools/file"
	"github.com/pardnchiu/agenvoy/internal/tools/guide"
	"github.com/pardnchiu/agenvoy/internal/tools/interactive"
	toolRegister "github.com/pardnchiu/agenvoy/internal/tools/register"
	toolScheduler "github.com/pardnchiu/agenvoy/internal/tools/scheduler"
	toolSearcher "github.com/pardnchiu/agenvoy/internal/tools/searcher"
	toolTypes "github.com/pardnchiu/agenvoy/internal/tools/types"

	"github.com/pardnchiu/agenvoy/internal/tools/fetchPage"
	_ "github.com/pardnchiu/agenvoy/internal/tools/revision"
)

func init() {
	registSearchConversationHistory()

	external.Register()
	fetchPage.Register()
	file.Register()
	errorMemory.Register()
	toolScheduler.Register()
	toolSearcher.Register()
	interactive.Register()
	guide.Register()

	registRunCommand()
	registDownloadFile()
	registOpenFile()

	toolRegister.RegistGroup("api_", func(ctx context.Context, e *toolTypes.Executor, name string, args json.RawMessage) (string, error) {
		if e.APIToolbox == nil || !e.APIToolbox.IsExist(name) {
			return "", fmt.Errorf("not exist: %s", name)
		}

		var params map[string]any
		if err := json.Unmarshal(args, &params); err != nil {
			return "", fmt.Errorf("json.Unmarshal: %w", err)
		}
		return e.APIToolbox.Execute(ctx, name, params)
	})

	toolRegister.RegistGroup("script_", func(ctx context.Context, e *toolTypes.Executor, name string, args json.RawMessage) (string, error) {
		if e.ScriptToolbox == nil || !e.ScriptToolbox.IsExist(name) {
			return "", fmt.Errorf("not exist: %s", name)
		}
		return e.ScriptToolbox.Execute(ctx, name, args, e.WorkDir)
	})

	toolRegister.RegistGroup("ext_", func(ctx context.Context, e *toolTypes.Executor, name string, args json.RawMessage) (string, error) {
		if e.ExtAPIToolbox != nil && e.ExtAPIToolbox.IsExist(name) {
			var params map[string]any
			if err := json.Unmarshal(args, &params); err != nil {
				return "", fmt.Errorf("json.Unmarshal: %w", err)
			}
			return e.ExtAPIToolbox.Execute(ctx, name, params)
		}
		if e.ExtScriptToolbox != nil && e.ExtScriptToolbox.IsExist(name) {
			return e.ExtScriptToolbox.Execute(ctx, name, args, e.WorkDir)
		}
		return "", fmt.Errorf("not exist: %s", name)
	})

	// * generated by agent, need to be checked and optimized by human
	calculate.Register()
}
